### PR TITLE
TASK: Add Packages/Neos to cdpath

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
TBH: I have no clue of that is needed and/or helps anything. Seemed a good idea, though. :)

**Comment by kdambekalns** [comment]
Ping, @skurfuerst :)

**Comment by kdambekalns** [comment]
@skurfuerst should I close this, or is there any interest in this change left?

**Comment by kdambekalns** [comment]
whatever…

**Comment by skurfuerst** [comment]
I'll merge it. sorry for not seeing it!

**Pull request merged**
